org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
neo_version=21.4.38-beta
neo_version_range=[21.4,)
loader_version_range=[2,)
mapping_channel=official
mapping_version=1.21.4

mod_id=alphaskins
mod_name=Alphaskins
mod_license=GPL3
mod_version=1.21-4.2.0
mod_group_id=dev.mja00.alphaskins
mod_authors=mja00
mod_description=Enable transparency in skins


neogradle.subsystems.devLogin.enabled=true
